### ISSUE TITLE
web sdk 使用官方提供的解码工具解码自动上报数据失败

### ISSUE THREAD

**Issue by obf1313** [sensorsdata/sa-sdk-javascript#100]
https://www.sensorsdata.cn/tools/decode.html
使用这个网址对自动上报的数据解码失败

eyJpZGVudGl0aWVzIjp7IiRpZGVudGl0eV9jb29raWVfaWQiOiIxOTJkNzIyOWVlNzkwNC0wNjE1MDQ2Y2I4OTJhNTgtMjk2ZTQ5MzMtMjUwMTI1LTE5MmQ3MjI5ZWU4ZWU3IiwiJGlkZW50aXR5X2Fub255bW91c19pZCI6IjE5MmQ3MjI5ZWU3OTA0LTA2MTUwNDZjYjg5MmE1OC0yOTZlNDkzMy0yNTAxMjUtMTkyZDcyMjllZThlZTcifSwiZGlzdGluY3RfaWQiOiIxOTJkNzIyOWVlNzkwNC0wNjE1MDQ2Y2I4OTJhNTgtMjk2ZTQ5MzMtMjUwMTI1LTE5MmQ3MjI5ZWU4ZWU3IiwibGliIjp7IiRsaWIiOiJqcyIsIiRsaWJfbWV0aG9kIjoiY29kZSIsIiRsaWJfdmVyc2lvbiI6IjEuMjYuMTgifSwicHJvcGVydGllcyI6eyIkdGltZXpvbmVfb2Zmc2V0IjotNDgwLCIkc2NyZWVuX2hlaWdodCI6MTA4MCwiJHNjcmVlbl93aWR0aCI6MTkyMCwiJHZpZXdwb3J0X2hlaWdodCI6OTE5LCIkdmlld3BvcnRfd2lkdGgiOjk2OSwiJGxpYiI6ImpzIiwiJGxpYl92ZXJzaW9uIjoiMS4yNi4xOCIsIiRsYXRlc3RfdHJhZmZpY19zb3VyY2VfdHlwZSI6InVybOeahGRvbWFpbuino%2BaekOWksei0pSIsIiRsYXRlc3Rfc2VhcmNoX2tleXdvcmQiOiJ1cmznmoRkb21haW7op6PmnpDlpLHotKUiLCIkbGF0ZXN0X3JlZmVycmVyIjoidXJs55qEZG9tYWlu6Kej5p6Q5aSx6LSlIiwiJGVsZW1lbnRfdHlwZSI6ImJ1dHRvbiIsIiRlbGVtZW50X2NsYXNzX25hbWUiOiJhbnQtYnRuIGNzcy1kZXYtb25seS1kby1ub3Qtb3ZlcnJpZGUteGpuZXg0IGFudC1idG4tcHJpbWFyeSIsIiRlbGVtZW50X2NvbnRlbnQiOiLmlrDlu7oiLCIkdXJsIjoiaHR0cDovL2xvY2FsaG9zdDo4MDAwL3BsYXQtdGxpbmstbWd0L2RlbGl2ZXI%2FdGFiPTImY3VycmVudD0xJnBhZ2VTaXplPTEwIiwiJHVybF9wYXRoIjoiL3BsYXQtdGxpbmstbWd0L2RlbGl2ZXIiLCIkdGl0bGUiOiIiLCIkZWxlbWVudF9zZWxlY3RvciI6IiNyYy10YWJzLTAtcGFuZWwtMiA%2BIGRpdjpudGgtb2YtdHlwZSgyKSA%2BIGRpdjpudGgtb2YtdHlwZSgyKSA%2BIGRpdjpudGgtb2YtdHlwZSgxKSA%2BIGRpdjpudGgtb2YtdHlwZSgxKSA%2BIGRpdjpudGgtb2YtdHlwZSgxKSA%2BIGRpdjpudGgtb2YtdHlwZSgyKSA%2BIGRpdjpudGgtb2YtdHlwZSgxKSA%2BIGJ1dHRvbjpudGgtb2YtdHlwZSgxKSIsIiRlbGVtZW50X3BhdGgiOiJkaXYjcmMtdGFicy0wLXBhbmVsLTIgPiBkaXYgPiBkaXYgPiBkaXYgPiBkaXYgPiBkaXYgPiBkaXYgPiBkaXYgPiBidXR0b24iLCIkcGFnZV94Ijo3OTMsIiRwYWdlX3kiOjM2MCwiJGlzX2ZpcnN0X2RheSI6ZmFsc2V9LCJhbm9ueW1vdXNfaWQiOiIxOTJkNzIyOWVlNzkwNC0wNjE1MDQ2Y2I4OTJhNTgtMjk2ZTQ5MzMtMjUwMTI1LTE5MmQ3MjI5ZWU4ZWU3IiwidHlwZSI6InRyYWNrIiwiZXZlbnQiOiIkV2ViQ2xpY2siLCJ0aW1lIjoxNzMwNDI5NTMwMTI1LCJfdHJhY2tfaWQiOjg4MTAzMDEyNiwiX2ZsdXNoX3RpbWUiOjE3MzA0Mjk1MzAxMjZ9&ext=crc%3D-1150567632

报错信息如下：
decode.html:170 Uncaught InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at HTMLInputElement.onclick (decode.html:170:220)

**Comment by lxdonge** [comment]
来信收到。thanks.
