### ISSUE TITLE
使用 import 方式 引入，应该就不需要填写 SDK_URL, 但不填，会报错啊。

### ISSUE THREAD

**Issue by huyansheng3** [sensorsdata/sa-sdk-javascript#11]
![image](https://user-images.githubusercontent.com/11534583/32926388-94356b96-cb0c-11e7-9ff2-79968aebb60f.png)

代码里 replace 没判断好吧。

**Comment by taoabc** [comment]
同这个问题

**Comment by sunsly1991** [comment]
m

**Comment by riyue** [comment]
不好意思，我的错，因为最新版（1.9.0开始）的sdk，把点击图的渲染的代码拆出来作为了一个新文件，所以需要指定点击图渲染的代码的路径，如果没有指定的话，会从sdk_url指定的url目录里直接找heatmap.min.js。所以，这里需要设置一下新的配置heatmap_url 就可以了。

**Comment by zhongqc** [comment]
我觉得这个heatmap_url还是需要重新设计下，如果通过webpack等方式进行打包的话大概率会把这两个js文件直接打到一个package文件中，而不大可能会采用异步加载的方式加载heatmap.js，是否后续会重新考虑这里的加载方式

**Comment by riyue** [comment]
> 我觉得这个heatmap_url还是需要重新设计下，如果通过webpack等方式进行打包的话大概率会把这两个js文件直接打到一个package文件中，而不大可能会采用异步加载的方式加载heatmap.js，是否后续会重新考虑这里的加载方式

考虑heatmap文件比较大，且仅在在点击图渲染模式下才会去加载，所以是跟sensorsdata.min.js分开的。目前这个文件，我们会自动匹配我们的cdn地址，可以不用再配置这个地址了。
