### ISSUE TITLE
异步引入时 sa.init 未提前注册

### ISSUE THREAD

**Issue by huyansheng3** [sensorsdata/sa-sdk-javascript#14]
var ifs = ['track', 'quick', 'register', 'registerPage', 'registerOnce', 'trackSignup', 'trackAbtest',
        'setProfile', 'setOnceProfile', 'appendProfile', 'incrementProfile', 'deleteProfile', 'unsetProfile',
        'identify', 'login', 'logout', 'trackLink', 'clearAllRegister', 'getAppStatus'
      ];

异步引入时，没有在同步的代码中注册 sa.init，导致代码中 sa.init 可能没有初始化就报错了。

**Comment by huyansheng3** [comment]
我的问题，异步引入直接进行 init 了

**Comment by riyue** [comment]
异步加载sdk时候，我们没有提供init方法，init方法仅限在import，require等方式加载时候使用
