### ISSUE TITLE
_和lodash冲突

### ISSUE THREAD

**Issue by simbawus** [sensorsdata/sa-sdk-javascript#15]
sdk里面定义的_ 对象和lodash库冲突，这个问题该怎么解决呢？

**Comment by riyue** [comment]
sdk里的_的作用域是在sdk里的，跟外面的lodash不应该冲突啊？

**Comment by simbawu610** [comment]
@riyue sdk里的_ 挂在windows上了

**Comment by riyue** [comment]
不可能啊，您在仔细看下。 sdk里是这么写的  var _ = sd._ = {};  
我实际测试 window._ 也是 undefined

**Comment by simbawus** [comment]
@riyue 你在console里写_.isEmptyObject()，看这个方法存不存在，这个方法是你们sdk里的，我这边是存在的

**Comment by riyue** [comment]
我测试没问题，你是怎么引入的sdk，你具体是哪个客户，方便微信具体了解下情况吗

**Comment by simbawus** [comment]
我是薄荷前端工程师，可以加我微信simbawu610

**Comment by riyue** [comment]
我已经在薄荷的客户群里了，麻烦您也加下
