### ISSUE TITLE
sdk 体积能压缩下吗? 现在似乎有点太大了

### ISSUE THREAD

**Issue by acrazing** [sensorsdata/sa-sdk-javascript#18]
![image](https://user-images.githubusercontent.com/10029810/43620533-caa5316e-9705-11e8-81ac-e91fda7d7f9d.png)

一个日志库就55k, 能不能做成标准的 commonjs 包, 然后按需引用? 或者做一个轻量版?

**Comment by riyue** [comment]
因为有很多预置属性的获取，导致了代码增加。
纯数据发送的代码量并不大。但是考虑到数据完整性，还是需要这些预置属性的。所以不太好缩减。
后续我们会考虑做一个只有数据发送功能的sdk，来满足你的需求。

**Comment by acrazing** [comment]
什么样的属性获取会产生压缩后还有50k的大小呢？
如果有依赖可以考虑npm包里面发布一个标准的commonjs包呀，有些依赖可能会是项目本身也需要的，就不用产生两个副本了，比如像moment之类

**Comment by riyue** [comment]
现在代码中本来就没有两个副本。而且我们没有moment之类的大模块（仅限一个json2），只有很多 _ 开头的功能方法。所以不存在两个副本的说法。

不知道你有没有用过我们sdk，我们的预置事件和属性是比较丰富的，通过预置事件和属性，客户可以少写大量代码，如果只是一个纯发数据的sdk，那所有的埋点都需要客户手动去写，那我们就卖不出去了。

99%的客户需求是，能不能自动采集页面地址，能不能自动判断是否首日，有没有点击图的功能。

比如：我们所有事件都会有是否首日属性的判断，所有事件都会有最近一次广告来源，最近一次流量来源，最近一次前向地址的判断。。类似这样的，还有很多针对单独某个事件的很多预置属性。类似这样的属性有很多，而这些需求是导致代码增大的主要愿意之一。

也就是说，没压缩50k的代码，里有成百上千个功能在里面，而不是只有十几个功能，如果只有十几个功能，那就没有什么耦合了，模块就很好做了。但如果有成百上千个功能，也就是本来每个功能的代码量就不大，还要再去细分，就没有什么意义了，可能你写个配置的代码量都和功能的代码量一样大了。那还不如再提供一个精简版，只有发数据的功能就好了。
