### ISSUE TITLE
使用vue后，相同路由不同参数的页面统计问题

### ISSUE THREAD

**Issue by SnowWinterMaye** [sensorsdata/sa-sdk-javascript#21]
在我们系统里，使用了vue-router，mode为 history
比如：   `/order/orderDetail/123`
            `/order/orderDetail/456`
我们希望这两个路由在统计时 作为同一个页面处理。
目前这两种被记录下来的 $url_path  分别为 
 `/order/orderDetail/123 `和 `/order/orderDetail/456`
但是按照可视化界面的 事件分析来处理，无法合并这两种路由地址。
即使按照正则表达式的方式作为查询指标，也无法合并这种类型的路由地址
问题:
- 在埋点时，是否可以自定义扩展属性 额外记录属性来处理此类问题
- 可视化 事件分析的 指标里 ，有什么其他方式来实现此类操作？
- 自定义查询里可以通过某些SQL来解决此类问题，但如何应用到可视化的事件分析当中作为查询指标？

期待回复，谢谢！

**Comment by riyue** [comment]
不好意思，刚看到，下次着急的问题，直接在我们微信群里提问就好了。我们和客户都有微信群的。这个在事件分析里是可以合并的，或者做成一个虚拟事件都是可以的。
