### ISSUE TITLE
小程序使用插件功能后，sa-sdk-javascript因为覆写了 App Page 导致报错

### ISSUE THREAD

**Issue by jiankafei** [sensorsdata/sa-sdk-javascript#22]
小程序使用插件功能后，sa-sdk-javascript因为覆写了 App Page 导致报错

**Comment by jiangyanyun** [comment]
可以使用我们的小程序插件版sdk，具体请参考集成文档https://www.sensorsdata.cn/manual/mp_sdk_plugin.html
