### ISSUE TITLE
sa-sdk-javascript

### ISSUE THREAD

**Issue by lenxuelenxue** [sensorsdata/sa-sdk-javascript#23]
sa-sdk-javascript有没有专门用于vue项目的sdk?

**Comment by jiangyanyun** [comment]
可以从 npm 获取 sdk ， npm install sa-sdk-javascript，在vue的入口文件引入sdk包文件，调用init方法进行初始化sdk，可以参考我们的集成文档https://www.sensorsdata.cn/manual/js_sdk.html
