### ISSUE TITLE
能在代码里不使用window对象吗

### ISSUE THREAD

**Issue by LiuWeiMr** [sensorsdata/sa-sdk-javascript#24]
看到代码内部使用里很多次window对象，在脱离浏览器很难测试依赖了这个模块的功能，能不使用window对象吗

**Comment by rainyjune** [comment]
这个 JS SDK是为浏览器端设计的，核心功能依赖于 window 对象。你是想为这个 SDK 做单元测试吗？

**Comment by LiuWeiMr** [comment]
我是想在非浏览器的环境测试我开发的模块，我的模块引用了你的模块。。。可以做一些全局的闭包替换window 对象吗




| |
刘伟
邮箱：nmgliuw@163.com
|

签名由 网易邮箱大师 定制

在2019年05月31日 19:19，Kang Chen 写道：

这个 JS SDK是为浏览器端设计的，核心功能依赖于 window 对象。你是想为这个 SDK 做单元测试吗？

**Comment by riyue** [comment]
目前我们javascript-sdk是针对浏览器端设计的，不支持非浏览器端。后面会开发一款非浏览器端的sdk，需要等待一段时间
