### ISSUE TITLE
如何创建两个不同 server_url 的实例？

### ISSUE THREAD

**Issue by zhengqingxin** [sensorsdata/sa-sdk-javascript#27]
场景：同一个前端项目，需要给不同的数据项目打点。

请问如何创建两个不同 `server_url` 的实例？

**Comment by riyue** [comment]
不建议这么做，一个网站对应一个项目，如果一个网站对应两个项目，用户关联会存在问题，另外cookie里保存的id，以及最近一次等属性也是全局的，不能分开来看。如果非要这么做的话，可以在微信群里中提出需求，我们也有方案（但不建议）。
