### ISSUE TITLE
添加typescript类型声明文件

### ISSUE THREAD

**Issue by zhayes** [sensorsdata/sa-sdk-javascript#28]
建议添加typescript类型声明文件，以支持TS开发的的import导入

**Comment by rainyjune** [comment]
如果在引入 sa-sdk-javascript 后遇到了 `Could not find a declaration file for module 'sa-sdk-javascript'` 提示信息，原因是我们没有为这个包提供 typescript 建议的声明文件，这个声明文件正在开发中。

如果你正在用 ts 开发项目，引入神策JS SDK时可以用 require() 方式加载：
```
const sensors = require('sa-sdk-javascript');
```
ES 6格式的SDK正在开发中。
