### ISSUE TITLE
getIOSVersion报错

### ISSUE THREAD

**Issue by failedUser** [sensorsdata/sa-sdk-javascript#36]
我们app的ua是 xxx/1.0(com.xxx.xxx 4.3.0; iPhone 7 Plus 1242x2208; iOS 12.2; zh_CN) /sa-sdk-ios

getIOSVersion 匹配不出来 导致ios页面打不开

**Comment by failedUser** [comment]
版本1.15.16

**Comment by riyue** [comment]
已经修复，正在上线
