### ISSUE TITLE
请问是否考虑使用typescript

### ISSUE THREAD

**Issue by FangyimingLode** [sensorsdata/sa-sdk-javascript#42]
请问是否有计划支持typescript

**Comment by riyue** [comment]
在开发了，你是要d.ts的类型声明文件吧？

**Comment by riyue** [comment]
> 请问是否有计划支持typescript

在开发了，你是要d.ts的类型声明文件吧？

**Comment by AlanKnightly** [comment]
Hi，@riyue  ，我司最近在使用神策的web sdk，umd方式， 请问目前有其它方式引入神策实例的type嘛？

**Comment by WinmezzZ** [comment]
> > 请问是否有计划支持typescript
> 
> 在开发了，你是要d.ts的类型声明文件吧？

23年了。一个类型声明文件这么困难吗？

**Comment by FangyimingLode** [comment]
> > > 请问是否有计划支持typescript
> > 
> > 
> > 在开发了，你是要d.ts的类型声明文件吧？
> 
> 23年了。一个类型声明文件这么困难吗？

哈哈哈
