### ISSUE TITLE
建议屏蔽npm仓库中的demo文件夹

### ISSUE THREAD

**Issue by daysv** [sensorsdata/sa-sdk-javascript#44]
目前通过npm install下载的包中， 约有18mb是demo文件夹，在node_modules中比较占用空间。
建议添加.npmignore文件屏蔽npm仓库中的demo

**Comment by riyue** [comment]
好的，我们下个版本就上

**Comment by daysv** [comment]
> 好的，我们下个版本就上

1.16.7 依然没有屏蔽

**Comment by WangShuXian6** [comment]
demo 又不会打包到生产文件中，根本没必要去掉。
作为重要的使用示例，绝对不能去掉。
