### ISSUE TITLE
关于Ts文件能否明细化

### ISSUE THREAD

**Issue by McPorkChop** [sensorsdata/sa-sdk-javascript#47]
现在官方提供的.d.ts文件中存在大量的any和object对开发完全没有帮助。

**Comment by bugfix2020** [comment]
确实是大量any 毫无帮助

**Comment by bugfix2020** [comment]
真·anyscript
![image](https://user-images.githubusercontent.com/29813979/145789489-e5a85db4-c082-4a75-bf02-3f7942bee5b5.png)

**Comment by linqunhe** [comment]
hhh, anyscript ... 笑死了

**Comment by riyue** [comment]
因为客户场景太多，目前做了最大的兼容。导致参数的灵活性很大，会出现很多小众场景的参数兼容。所以出现了不少 any 。在 ng 版本 sdk 中我们将会去掉大部分兼容场景，是的 ts 更加确定。
