### ISSUE TITLE
全埋点上报一直报丢失属性的问题（pageX,pageY)

### ISSUE THREAD

**Issue by linqunhe** [sensorsdata/sa-sdk-javascript#55]
![wecom-temp-84f45f4e703d4ce8cb9b5de4dda4cb8e](https://user-images.githubusercontent.com/80025623/159832759-8d5d5e4f-d5bd-41a0-b5f2-72ea068c54a8.png)

**Comment by riyue** [comment]
估计是 SA 版本太低。麻烦在微信群中，寻找值班同学协助升级
