### ISSUE TITLE
通过import 引入 aes-encryption.min.js，提示文件依赖缺失?

### ISSUE THREAD

**Issue by EvanLin0** [sensorsdata/sa-sdk-javascript#63]
通过import 引入 aes-encryption.min.js，提示文件依赖缺失?
import '@/assets/sa-sensors-js/plugins/aes-encryption.min.js'
![image](https://user-images.githubusercontent.com/40919801/195281103-5558dfa2-9f33-4c77-b8ba-fd97acbcf7f5.png)

**Comment by riyue** [comment]
1. 目前插件暂不支持ES6 import 引入方式，暂时通过 script 方式引入。
2. 如果着急的话请在微信群中找技术顾问联系我们研发进行针对性的定制改造。
3. 另外“插件重构 ES6 支持”的功能已经提测，预计最早这个月底会上ES6版本，也可以等待下。
