### ISSUE TITLE
v1.24.1 not work

### ISSUE THREAD

**Issue by Shawn-Cui** [sensorsdata/sa-sdk-javascript#64]
<img width="595" alt="image" src="https://user-images.githubusercontent.com/20104130/198028246-dee9b484-78ad-4bc9-a01a-610f8cb44a39.png">

**Comment by riyue** [comment]
package.json 中的写错了。把   "main": "dist/web/sensorsdata.min.js",
改成 /dist/web/sensorsdata.js 就可以了
正在发布v1.24.2 修复
