### ISSUE TITLE
H5分享以后会多出一条不同的distinctId的数据

### ISSUE THREAD

**Issue by duchaolin** [sensorsdata/sa-sdk-javascript#66]
比如自己distinctId是18430e80f3071-0c1709574cc3cf8-4b6e1e6f-2073600-18430e80f313f6，仅仅是分享给自己（或者其他人以后）但是不点击进去，但是此时fkf上就会多一条不同的distinctId数据

**Comment by riyue** [comment]
我预测你用了site-linker插件，这个插件的功能是用来做多域名打通，你们应该是使用这个插件了
