### ISSUE TITLE
版本 v1.24.2 typescript 的 .d.ts无法读取

### ISSUE THREAD

**Issue by xiamu14** [sensorsdata/sa-sdk-javascript#67]
问题描述：
项目 install 以后，下载了最新的 v1.24.2 版本，然后 ts 报错，提示没有类型文件

问题原因：
1.24.2 的代码类型文件没有在 package.json 里定义，同时类型文件和 main 字段定义的入口文件也不一致

**Comment by riyue** [comment]
感谢，这个问题会在 v1.24.3 中修复
