### ISSUE TITLE
批量发送数组会有null的情况

### ISSUE THREAD

**Issue by iamtang** [sensorsdata/sa-sdk-javascript#76]
![image](https://user-images.githubusercontent.com/13829341/225860255-79c72147-8f71-4d7e-b24b-3aef56f3cb89.png)、

非必现

如果有存在null情况

有没有发送请求前的拦截器可以清空null的情况？或者有什么方式可以清除null数据

**Comment by NickDone** [comment]
> ![image](https://user-images.githubusercontent.com/13829341/225860255-79c72147-8f71-4d7e-b24b-3aef56f3cb89.png)、
> 
> 非必现
> 
> 如果有存在null情况
> 
> 有没有发送请求前的拦截器可以清空null的情况？或者有什么方式可以清除null数据

你用的是哪个版本的 SDK？

**Comment by lxdonge** [comment]
来信收到。thanks.

**Comment by lxdonge** [comment]
> 
抱歉，我们目前暂时无法复现该问题，如果有稳定复现步骤，您可以开新的 issue 我们来进行追踪和修复，如果您是使用的自己的后端，建议后端入库时删除 null 。 如果您使用的是神策产品，建议您直接找技术顾问发起售后工单。
