### ISSUE TITLE
general-encryption 非对称加密 为什么需要自建服务端解密？

### ISSUE THREAD

**Issue by Resen4983** [sensorsdata/sa-sdk-javascript#79]
# 自定义加密 https://github.com/sensorsdata/sa-sdk-javascript/tree/master/dist/web/plugin/general-encryption
该插件加密后，需使用自建服务端进行解密，解密后再同步到神策服务端。
----------
使用sm2 和 sm4 混合加密，可以神策服务端创建好公钥，数据上报后神策服务端直接用私钥解密不行吗？ 为什么非得自建服务端，然后再用 logagent 从服务端发送到神策服务器。

**Comment by lxdonge** [comment]
我们旨在提供通用的对称+非对称加密方式，不限于 sm2+sm4，由于客户加密要求存在差异，需要客户自行进行加解密。
