### ISSUE TITLE
微信浏览器中h5页面使用初始化后手机会发烫

### ISSUE THREAD

**Issue by newlonbachev** [sensorsdata/sa-sdk-javascript#82]

**Comment by newlonbachev** [comment]
使用uniApp开发的h5会出现上述问题

**Comment by lxdonge** [comment]
手机发烫可能是多个原因，一般来说是由于 CPU 或 GPU 处于高频运行导致的。 SDK 代码中无任何需要大计算量的代码，您目前提供的信息无法佐证是由于 SDK 引起的 CPU 高频运行。可以尝试检查打开其他页面或者去除 SDK 后是否有相同现象。
