### ISSUE TITLE
页面访问时长回累加的问题

### ISSUE THREAD

**Issue by supergenge** [sensorsdata/sa-sdk-javascript#83]
下面是几条上传的数据的示例，每隔几分钟，都会出现一次用户访问的页面的时长会在之前的基础上累加的现象，导致某个页面的访问时长达到几万秒，然而两个几万秒访问时长的数据之间的time只相隔了几分钟，且这几分钟内，又上报了几条正常的pageleave事件（访问时长几十秒），sdk版本是1.25.4
{"identities":{"$identity_cookie_id":"18894e20aab316-0af7ec55af3b59-26031d51-2073600-18894e20aac10d2","$identity_login_id":"yinlz01"},"distinct_id":"yinlz01","lib":{"$lib":"js","$lib_method":"code","$lib_version":"1.25.4"},"properties":{"$timezone_offset":32,"$screen_height":1080,"$screen_width":1920,"$viewport_height":1040,"$viewport_width":2133,"$lib":"js","$lib_version":"1.25.4","$latest_traffic_source_type":"直接流量","$latest_search_keyword":"未取到值_直接打开","$latest_referrer":"","appId":"1428166773177380866","$title":"工作台","$url":"https://portal.easthope.cn/workbench","$url_path":"/workbench","$referrer_host":"portal.easthope.cn","$referrer":"https://portal.easthope.cn/user/login?redirect=%2Fworkbench","$viewport_position":0,"event_duration":51412.053,"$is_first_day":false},"login_id":"yinlz01","anonymous_id":"18894e20aab316-0af7ec55af3b59-26031d51-2073600-18894e20aac10d2","type":"track","event":"$WebPageLeave","time":1686185881863,"_track_id":445581869,"_flush_time":1686185881869}

{"identities":{"$identity_cookie_id":"18894e20aab316-0af7ec55af3b59-26031d51-2073600-18894e20aac10d2","$identity_login_id":"yinlz01"},"distinct_id":"yinlz01","lib":{"$lib":"js","$lib_method":"code","$lib_version":"1.25.4"},"properties":{"$timezone_offset":32,"$screen_height":1080,"$screen_width":1920,"$viewport_height":1041,"$viewport_width":2133,"$lib":"js","$lib_version":"1.25.4","$latest_traffic_source_type":"直接流量","$latest_search_keyword":"未取到值_直接打开","$latest_referrer":"","appId":"1428166773177380866","$title":"工作台","$url":"https://portal.easthope.cn/workbench","$url_path":"/workbench","$referrer_host":"portal.easthope.cn","$referrer":"https://portal.easthope.cn/portal","$viewport_position":0,"event_duration":5.066,"$is_first_day":false},"login_id":"yinlz01","anonymous_id":"18894e20aab316-0af7ec55af3b59-26031d51-2073600-18894e20aac10d2","type":"track","event":"$WebPageLeave","time":1686185836109,"_track_id":288506109,"_flush_time":1686185836109}

{"identities":{"$identity_cookie_id":"18894e20aab316-0af7ec55af3b59-26031d51-2073600-18894e20aac10d2","$identity_login_id":"yinlz01"},"distinct_id":"yinlz01","lib":{"$lib":"js","$lib_method":"code","$lib_version":"1.25.4"},"properties":{"$timezone_offset":32,"$screen_height":1080,"$screen_width":1920,"$viewport_height":1041,"$viewport_width":2133,"$lib":"js","$lib_version":"1.25.4","$latest_traffic_source_type":"直接流量","$latest_search_keyword":"未取到值_直接打开","$latest_referrer":"","appId":"1428166773177380866","$title":"工作台","$url":"https://portal.easthope.cn/workbench","$url_path":"/workbench","$referrer_host":"portal.easthope.cn","$referrer":"https://portal.easthope.cn/portal","$viewport_position":0,"event_duration":0.646,"$is_first_day":false},"login_id":"yinlz01","anonymous_id":"18894e20aab316-0af7ec55af3b59-26031d51-2073600-18894e20aac10d2","type":"track","event":"$WebPageLeave","time":1686185830371,"_track_id":384740371,"_flush_time":1686185830371}

{"identities":{"$identity_cookie_id":"18894e20aab316-0af7ec55af3b59-26031d51-2073600-18894e20aac10d2","$identity_login_id":"yinlz01"},"distinct_id":"yinlz01","lib":{"$lib":"js","$lib_method":"code","$lib_version":"1.25.4"},"properties":{"$timezone_offset":32,"$screen_height":1080,"$screen_width":1920,"$viewport_height":1041,"$viewport_width":2133,"$lib":"js","$lib_version":"1.25.4","$latest_traffic_source_type":"直接流量","$latest_search_keyword":"未取到值_直接打开","$latest_referrer":"","appId":"1428166773177380866","$title":"工作台","$url":"https://portal.easthope.cn/workbench","$url_path":"/workbench","$referrer_host":"portal.easthope.cn","$referrer":"https://portal.easthope.cn/portal","$viewport_position":0,"event_duration":5.811,"$is_first_day":false},"login_id":"yinlz01","anonymous_id":"18894e20aab316-0af7ec55af3b59-26031d51-2073600-18894e20aac10d2","type":"track","event":"$WebPageLeave","time":1686185819957,"_track_id":272619957,"_flush_time":1686185819957}

{"identities":{"$identity_cookie_id":"18894e20aab316-0af7ec55af3b59-26031d51-2073600-18894e20aac10d2","$identity_login_id":"yinlz01"},"distinct_id":"yinlz01","lib":{"$lib":"js","$lib_method":"code","$lib_version":"1.25.4"},"properties":{"$timezone_offset":32,"$screen_height":1080,"$screen_width":1920,"$viewport_height":1040,"$viewport_width":2133,"$lib":"js","$lib_version":"1.25.4","$latest_traffic_source_type":"直接流量","$latest_search_keyword":"未取到值_直接打开","$latest_referrer":"","appId":"1428166773177380866","$title":"工作台","$url":"https://portal.easthope.cn/workbench","$url_path":"/workbench","$referrer_host":"portal.easthope.cn","$referrer":"https://portal.easthope.cn/user/login?redirect=%2Fworkbench","$viewport_position":0,"event_duration":51292.053,"$is_first_day":false},"login_id":"yinlz01","anonymous_id":"18894e20aab316-0af7ec55af3b59-26031d51-2073600-18894e20aac10d2","type":"track","event":"$WebPageLeave","time":1686185761863,"_track_id":553201864,"_flush_time":1686185761864}

**Comment by riyue** [comment]
这个问题，已经提交过了
