### ISSUE TITLE
a标签跳转，添加在a标签上的埋点点击事件会被cancel？

### ISSUE THREAD

**Issue by Phoebe-f** [sensorsdata/sa-sdk-javascript#84]
在某些环境下，给a标签添加埋点点击事件后，请求会发送，但是会被cancel掉，标签可以正常跳转，这是为什么呢？

**Comment by lxdonge** [comment]
可以描述得具体些吗？被 cancel 是是被什么 cancel

**Comment by Phoebe-f** [comment]
就是在a标签绑定了click事件触发埋点的点击事件，发送数据给后台。但是发送的请求从控制台的网络看会被cancel，后端并没有收到收据。如果在a标签加个定时器，就是先触发埋点的点击事件，再跳转，埋点事件就会正常发送。
