### ISSUE TITLE
url的domain解析失败

### ISSUE THREAD

**Issue by jikuanyu** [sensorsdata/sa-sdk-javascript#85]
```
<script charset='UTF-8' src="sensorsdata.min.js "></script>
<script>
	var sensors = window['sensorsDataAnalytic201505'];
	sensors.init({
  		server_url: 'http://192.168.144.148:8080/i?token=xxxxx&project=xxxxxx',
		is_track_single_page:true, // 单页面配置，默认开启，若页面中有锚点设计，需要将该配置删除，否则触发锚点会多触发 $pageview 事件
		use_client_time:true, 
  		send_type:'beacon',
                          
		heatmap: {
			//是否开启点击图，default 表示开启，自动采集 $WebClick 事件，可以设置 'not_collect' 表示关闭。
			clickmap:'default',
			//是否开启触达图，not_collect 表示关闭，不会自动采集 $WebStay 事件，可以设置 'default' 表示开启。
			scroll_notice_map:'not_collect'
		}   
	});
	sensors.quick('autoTrack');

sensors.quick('autoTrack', {
	platform:'h5'
})

```

base64解吗后

`{"identities":{"$identity_cookie_id":"18907131407842-0df0e65d68ffa6-4201571e-922320-18907131408f15"},"distinct_id":"18907131407842-0df0e65d68ffa6-4201571e-922320-18907131408f15","lib":{"$lib":"js","$lib_method":"code","$lib_version":"1.25.2"},"properties":{"$timezone_offset":-480,"$screen_height":366,"$screen_width":2520,"$viewport_height":366,"$viewport_width":2520,"$lib":"js","$lib_version":"1.25.2","$latest_traffic_source_type":"url的domain解析失败","$latest_search_keyword":"url的domain解析失败","$latest_referrer":"url的domain解析失败","$referrer":"","$url":"http://192.168.144.17/s/index.html","$url_path":"/s/index.html","$title":"","platform":"h5","$is_first_day":true,"$is_first_time":false,"$referrer_host":""},"anonymous_id":"18907131407842-0df0e65d68ffa6-4201571e-922320-18907131408f15","type":"track","event":"$pageview","time":1688040844502,"_track_id":884694503,"_flush_time":1688040844503}`

我哪里弄错了，期待你的回复。

**Comment by jikuanyu** [comment]
第一次接触，我知道需要使用域名访问。

**Comment by lxdonge** [comment]
将页面通过域名访问才能正常解析域名，ip地址访问无法正常解析域名。
