### ISSUE TITLE
如何埋点获取主页面下不同tab的浏览量

### ISSUE THREAD

**Issue by panroubing** [sensorsdata/sa-sdk-javascript#87]
我的需求是这样的：主页面上有两个tab子页面（a，b），现在只能埋到主页面的浏览次数，无法分辨出tab子页面a和tab子页面b的占比是多少。两个tab点击事件与主页面浏览量差异非常大，没办法用。

**Comment by riyue** [comment]
手动埋点。两个tab，怎么打开的，你自己知道的
