### ISSUE TITLE
能自定义触发采集吗？比如Input onChange事件这种

### ISSUE THREAD

**Issue by HahnBrunt** [sensorsdata/sa-sdk-javascript#89]
目前来看好像只有 只有Click、PageLeave、PageLoad这种才会触发采集

**Comment by HahnBrunt** [comment]
collect_input: (element_target: Element | undefined) => {
        if (
          typeof element_target?.tagName === 'string' &&
          element_target?.tagName.toLowerCase() === 'input'
        ) {
          return true
        }
      },
     这种能采集到input的content，但是触发并不是onchange

**Comment by riyue** [comment]
onchange 没做，可以自己做个插件嘛。功能随便扩展。
