### ISSUE TITLE
网页热力分析问题

### ISSUE THREAD

**Issue by chenHusky** [sensorsdata/sa-sdk-javascript#90]
在url上拼接上参数 ?sa-request-url=https://www.baidu.com&sa-request-type=1&sa-request-id=xss 网页顶部会出现热力分析操作栏，这个是界面不期望出现的， 请问下这个有没有参数可以关闭
![image](https://github.com/sensorsdata/sa-sdk-javascript/assets/50655754/28039c89-c562-46f4-b99b-7b97ad2e2e8c)

**Comment by lxdonge** [comment]
来信收到。thanks.

**Comment by riyue** [comment]
已经记录到需求中了。这个问题是一个冲突，有的人期望自动开启，有的人期望不要有入口。
大部分人还是期望，简单引入，全都自动来实现。所以如果要做成单独开启的话，需要考虑一下。已经加到需求中了
