### ISSUE TITLE
web端模块化引入sdk，首次进入网站都会提示输入用户密码，如何设置 token

### ISSUE THREAD

**Issue by xiaoqingComeOn** [sensorsdata/sa-sdk-javascript#91]
模块化引入sdk，首次进入网站都会提示输入用户密码，这个如何处理，
sdkInstance = await import('sa-sdk-javascript');
    sdkInstance.init({
      server_url:
        '地址',
      is_track_single_page: true, // 单页面配置，默认开启，若页面中有锚点设计，需要将该配置删除，否则触发锚点会多触发 $pageview 事件
      use_client_time: true,
      send_type: 'beacon',
      showLog: true,
      heatmap: {
        //是否开启点击图，default 表示开启，自动采集 $WebClick 事件，可以设置 'not_collect' 表示关闭。
        clickmap: 'default',
        //是否开启触达图，not_collect 表示关闭，不会自动采集 $WebStay 事件，可以设置 'default' 表示开启。
        scroll_notice_map: 'default'
      }
    });
<img width="323" alt="image" src="https://github.com/sensorsdata/sa-sdk-javascript/assets/36757399/1168289d-fefc-48e3-9c49-e6571e1aa6f8">

**Comment by riyue** [comment]
跟 SDK 没有关系，SDK 里没有这个

**Comment by lxdonge** [comment]
来信收到。thanks.
