### ISSUE TITLE
jsSDK1.26.7版本，webstay上报event_duration没有前面的$

### ISSUE THREAD

**Issue by white-shiro-bai** [sensorsdata/sa-sdk-javascript#93]
感谢开源维护者的时间

SDK： js
版本： 1.26.7

现象 ：开启scroll_notice_map后，$WebStay事件开始上报
在 properties 下 key ，event_duration 没有带前面的 $，而是直接上报了event_duration 与 文档 $event_duration的表述不一致。

期待： 与文档描述一致，使用 $event_duration 作为key。

问题数据示例：
`{
            "_flush_time": 1710216881504,
            "_track_id": 466912335,
            "anonymous_id": "18e30de0d7d889-07fda12f684bd9c-4c657b58-1638720-18e30de0d7e18f4",
            "distinct_id": "18e30de0d7d889-07fda12f684bd9c-4c657b58-1638720-18e30de0d7e18f4",
            "event": "$WebStay",
            "identities": {
                "$identity_cookie_id": "18e30de0d7d889-07fda12f684bd9c-4c657b58-1638720-18e30de0d7e18f4"
            },
            "lib": {
                "$lib": "js",
                "$lib_method": "code",
                "$lib_version": "1.26.7"
            },
            "properties": {
                "$is_first_day": true,
                "$latest_landing_page": "url的domain解析失败",
                "$latest_referrer": "url的domain解析失败",
                "$latest_referrer_host": "取值异常",
                "$latest_search_keyword": "url的domain解析失败",
                "$latest_traffic_source_type": "url的domain解析失败",
                "$lib": "js",
                "$lib_version": "1.26.7",
                "$screen_height": 960,
                "$screen_width": 1707,
                "$timezone_offset": -480,
                "$title": "测试埋点上报界面",
                "$url": "file:///D:/临时/sa-sdk-javascript-1.26.7/testjs.html",
                "$url_path": "/D:/临时/sa-sdk-javascript-1.26.7/testjs.html",
                "$viewport_height": 740,
                "$viewport_position": 0,
                "$viewport_width": 533,
                "event_duration": 9.705
            },
            "time": 1710216852335,
            "type": "track"
        }`

**Comment by fengandyun** [comment]
event_duration 是历史遗留问题。
神策大数据后台接收不带 $ 符号的 event_duration 并主动在后台添加 $ 符号入库。
如果单独使用 SDK 可以考虑添加，如果结合神策大数据平台使用 sdk 默认这样就可以。

**Comment by white-shiro-bai** [comment]
收到。非常感谢解答。
