### ISSUE TITLE
SDK预置的超时参数疑似问题

### ISSUE THREAD

**Issue by white-shiro-bai** [sensorsdata/sa-sdk-javascript#94]
在埋点上报时，使用image和beacon没有超时设定。这是符合浏览器特性的。
但是在para里预置了使用Ajax方式（AjaxSend）和batch_send:true方式（BatchSend）上报的超时设置，其中：
Ajax使用的是
`timeout: sdPara.datasend_timeout`
这个参数的预置值是8000
BatchSend方式上报，使用的是
`timeout: sdPara.batch_send.datasend_timeout`
这个参数的预置值是6000

问题：批量上报的超时时间比单条ajax上报的值给的还小。似乎有点问题。

**Comment by riyue** [comment]
确实，这个主要是当时单条发送在境外等网络不好的情况下，导致超时耗时很长，所以设置长了。理论上3秒内就可以。batch的发送用的少一些，并未出现境外网络不好导致的耗时很长，所以没修改默认值。
这个值可以自己调节。统一来说没法确定合理不合理，只是根据实际客户情况调节的。你可以配置成你认为合理的值。
