### ISSUE TITLE
访问次数如何计算

### ISSUE THREAD

**Issue by gaomAndximi** [sensorsdata/sa-sdk-javascript#97]
想问下老师，神策数据的网站访问次数是如何计算的？

**Comment by lxdonge** [comment]
来信收到。thanks.

**Comment by gaomAndximi** [comment]
老师你好，我们实验室最近想买一个成熟的埋点系统，我最近在调研。请问下神策埋点是怎么计算访问量的？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月05日 19:49 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [sensorsdata/sa-sdk-javascript] 访问次数如何计算 (Issue #97) |

来信收到。thanks.

**Comment by riyue** [comment]
请在微信群中咨询
