### ISSUE TITLE
Release 1.26.16  版本的sensorsdata.es6.min.js 会触发 eslint 语法检测，导致无法打包成功

### ISSUE THREAD

**Issue by 521guyu** [sensorsdata/sa-sdk-javascript#98]
Release 1.26.16  版本的sensorsdata.es6.min.js 会触发 eslint 语法检测，导致无法打包成功。1.26.15我也试了一下也会也会触发。npm start可以，但 npm run build 就无法打包成功。
我用的 框架是 create-react-app v5  
错误如下截图如下：

主要的就是：

1.Expected an assignment or function call and instead saw an expression  no-unused-expressions
2.sensorsDataAnalytic201505' is not defined    
3.Unexpected use of 'location'        no-restricted-globals

最后我忽略了该文件的eslint 语法检测 才解决。在根目录下新建一个 .eslintignore 文件写上：
`
sensorsdata.es6.min.js`

**Comment by lxdonge** [comment]
来信收到。thanks.
