### ISSUE TITLE
Property 'registerPropertyPlugin' does not exist on type 'typeof sensors'

### ISSUE THREAD

**Issue by bing-10** [sensorsdata/sa-sdk-javascript#99]
VUE3+TS项目中调用 `sensors.registerPropertyPlugin` 方法时报错：
Property 'registerPropertyPlugin' does not exist on type 'typeof sensors'
请问如何解决？

**Comment by riyue** [comment]
可以在微信群中联系

**Comment by bing-10** [comment]
请问微信群怎么加呢？
